// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class BloodTypePhuocNh
{
    public int BloodTypePhuocNhid { get; set; }

    public string TypeName { get; set; }

    public string RhFactor { get; set; }

    public bool? IsUniversalDonor { get; set; }

    public virtual ICollection<StudentHealthProfilePhuocNh> StudentHealthProfilePhuocNhs { get; set; } = new List<StudentHealthProfilePhuocNh>();
}