// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class HealthCheckStudentTinVt
{
    public Guid HealthCheckStudentTinVtid { get; set; }

    public Guid SessionId { get; set; }

    public Guid StudentId { get; set; }

    public decimal HeightCm { get; set; }

    public decimal WeightKg { get; set; }

    public decimal? Bmiscore { get; set; }

    public decimal? VisionLeft { get; set; }

    public decimal? VisionRight { get; set; }

    public string BloodPressure { get; set; }

    public bool? AbnormalFlag { get; set; }

    public DateTime? ResultSentDate { get; set; }

    public bool? ConsultationRequired { get; set; }

    public DateTime? ConsultationScheduleDate { get; set; }

    public string Remarks { get; set; }

    public virtual HealthCheckSessionTinVt Session { get; set; }
}