// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class HealthCheckSessionTinVt
{
    public Guid HealthCheckSessionTinVtid { get; set; }

    public string SessionCode { get; set; }

    public string Title { get; set; }

    public DateTime NotificationDate { get; set; }

    public DateTime ConsentDeadline { get; set; }

    public DateTime ScheduledCheckDate { get; set; }

    public int TotalStudentsExpected { get; set; }

    public int? TotalStudentsChecked { get; set; }

    public bool? IsNotificationSent { get; set; }

    public bool? IsResultSent { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ICollection<HealthCheckStudentTinVt> HealthCheckStudentTinVts { get; set; } = new List<HealthCheckStudentTinVt>();
}