// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class MedicalSupplyQuanNm
{
    public int MedicalSupplyQuanNmid { get; set; }

    public int CategoryId { get; set; }

    public string SupplyName { get; set; }

    public string Unit { get; set; }

    public int? QuantityAvailable { get; set; }

    public int? ReorderLevel { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public string Supplier { get; set; }

    public double? StorageTemperature { get; set; }

    public bool? IsControlledItem { get; set; }

    public bool? IsOutOfStock { get; set; }

    public virtual SupplyCategoryQuanNm Category { get; set; }
}