// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class MedicationTypeHienDh
{
    public int MedicationTypeHienDhid { get; set; }

    public string Name { get; set; }

    public bool RequiresPrescription { get; set; }

    public string UsageMethod { get; set; }

    public string Unit { get; set; }

    public virtual ICollection<MedicationSubmissionHienDh> MedicationSubmissionHienDhs { get; set; } = new List<MedicationSubmissionHienDh>();
}