// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class MedicationSubmissionHienDh
{
    public int MedicationSubmissionHienDhid { get; set; }

    public int StudentId { get; set; }

    public int ParentId { get; set; }

    public int MedicationTypeId { get; set; }

    public DateTime SubmissionDate { get; set; }

    public string Dosage { get; set; }

    public int? FrequencyPerDay { get; set; }

    public int? DurationDays { get; set; }

    public bool? IsDoctorNoteIncluded { get; set; }

    public bool? RequiresSupervision { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Note { get; set; }

    public virtual MedicationTypeHienDh MedicationType { get; set; }

    public virtual Parent Parent { get; set; }

    public virtual Student Student { get; set; }
}