// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class MedicalEventNguyenVq
{
    public int MedicalEventNguyenVqid { get; set; }

    public int? StudentId { get; set; }

    public int? MedicalEventTypeId { get; set; }

    public DateTime EventDateTime { get; set; }

    public string Situation { get; set; }

    public int? SeverityLevel { get; set; }

    public bool? HasGoneHospitalTransfer { get; set; }

    public int? HandledByNurseId { get; set; }

    public bool? HasParentBeenInformed { get; set; }

    public double? Temperature { get; set; }

    public int? PulseRate { get; set; }

    public virtual SchoolNurse HandledByNurse { get; set; }

    public virtual MedicalEventTypeNguyenVq MedicalEventType { get; set; }

    public virtual Student Student { get; set; }
}