// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class MedicalEventTypeNguyenVq
{
    public int MedicalEventTypeNguyenVqid { get; set; }

    public string TypeName { get; set; }

    public bool IsEmergency { get; set; }

    public int? DefaultSeverityLevel { get; set; }

    public virtual ICollection<MedicalEventNguyenVq> MedicalEventNguyenVqs { get; set; } = new List<MedicalEventNguyenVq>();
}