// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class Parent
{
    public int ParentId { get; set; }

    public int? UserAccountId { get; set; }

    public string Occupation { get; set; }

    public string RelationshipToStudent { get; set; }

    public virtual ICollection<MedicationSubmissionHienDh> MedicationSubmissionHienDhs { get; set; } = new List<MedicationSubmissionHienDh>();

    public virtual UserAccount UserAccount { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}