// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class SchoolNurse
{
    public int NurseId { get; set; }

    public int? UserAccountId { get; set; }

    public string CertificationCode { get; set; }

    public string Department { get; set; }

    public virtual ICollection<MedicalEventNguyenVq> MedicalEventNguyenVqs { get; set; } = new List<MedicalEventNguyenVq>();

    public virtual UserAccount UserAccount { get; set; }

    public virtual ICollection<VaccinationSessionKhoaNd> VaccinationSessionKhoaNds { get; set; } = new List<VaccinationSessionKhoaNd>();
}