// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class StudentHealthProfilePhuocNh
{
    public int StudentHealthProfilePhuocNhid { get; set; }

    public int StudentId { get; set; }

    public int? BloodTypePhuocNhid { get; set; }

    public double? HeightCm { get; set; }

    public double? WeightKg { get; set; }

    public double? VisionLeft { get; set; }

    public double? VisionRight { get; set; }

    public double? HearingScore { get; set; }

    public bool? HasAllergy { get; set; }

    public bool? HasDisability { get; set; }

    public bool? HasSurgeryHistory { get; set; }

    public DateTime? LastCheckupDate { get; set; }

    public virtual BloodTypePhuocNh BloodTypePhuocNh { get; set; }

    public virtual Student Student { get; set; }
}