// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public int? UserAccountId { get; set; }

    public string StudentCode { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string ClassName { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<MedicalEventNguyenVq> MedicalEventNguyenVqs { get; set; } = new List<MedicalEventNguyenVq>();

    public virtual ICollection<MedicationSubmissionHienDh> MedicationSubmissionHienDhs { get; set; } = new List<MedicationSubmissionHienDh>();

    public virtual ICollection<StudentHealthProfilePhuocNh> StudentHealthProfilePhuocNhs { get; set; } = new List<StudentHealthProfilePhuocNh>();

    public virtual UserAccount UserAccount { get; set; }

    public virtual ICollection<VaccinationStudentKhoaNd> VaccinationStudentKhoaNds { get; set; } = new List<VaccinationStudentKhoaNd>();

    public virtual ICollection<Parent> Parents { get; set; } = new List<Parent>();
}