// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class SupplyCategoryQuanNm
{
    public int SupplyCategoryQuanNmid { get; set; }

    public string CategoryName { get; set; }

    public bool IsMedicalUse { get; set; }

    public bool RequiresColdStorage { get; set; }

    public virtual ICollection<MedicalSupplyQuanNm> MedicalSupplyQuanNms { get; set; } = new List<MedicalSupplyQuanNm>();
}