// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class VaccinationStudentKhoaNd
{
    public int VaccinationStudentKhoaNdid { get; set; }

    public int VaccinationSessionId { get; set; }

    public int StudentId { get; set; }

    public bool? IsNotificationSent { get; set; }

    public DateTime? NotificationSentDate { get; set; }

    public string ConsentStatus { get; set; }

    public DateTime? ConsentReceivedDate { get; set; }

    public bool? IsVaccinated { get; set; }

    public DateOnly? VaccinationDate { get; set; }

    public string SideEffects { get; set; }

    public virtual Student Student { get; set; }

    public virtual VaccinationSessionKhoaNd VaccinationSession { get; set; }
}