// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class VaccinationSessionKhoaNd
{
    public int VaccinationSessionKhoaNdid { get; set; }

    public int? VaccineId { get; set; }

    public DateOnly? SessionDate { get; set; }

    public int? ConductedBy { get; set; }

    public int? TotalStudentsPlanned { get; set; }

    public int? TotalVaccinated { get; set; }

    public int? SideEffectsReported { get; set; }

    public bool? RequiresParentConsent { get; set; }

    public bool? IsCompleted { get; set; }

    public string VaccineBatchNumber { get; set; }

    public DateOnly? VaccineExpiryDate { get; set; }

    public virtual SchoolNurse ConductedByNavigation { get; set; }

    public virtual ICollection<VaccinationStudentKhoaNd> VaccinationStudentKhoaNds { get; set; } = new List<VaccinationStudentKhoaNd>();

    public virtual VaccineKhoaNd Vaccine { get; set; }
}