// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.TinVT.Models;

public partial class VaccineKhoaNd
{
    public int VaccineKhoaNdid { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public int? EffectiveDurationMonths { get; set; }

    public bool? RequiresMultipleDoses { get; set; }

    public virtual ICollection<VaccinationSessionKhoaNd> VaccinationSessionKhoaNds { get; set; } = new List<VaccinationSessionKhoaNd>();
}